name: flutter_mvvm_template
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  go_router: ^14.8.1
  provider: ^6.1.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - .env

